[programs.devnet]
gif_storage = "DCmY7MUPZha2Z349ipoJPmAud93K2sfdJSnVHG6xXNFN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/mcreteur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
